name: Periodic test
on:
  schedule:
    - cron: "17 1 * * *" # run every day at 1:17 am

jobs:
  cron_test:
    name: Scheduled test
    uses: gbetous-swir/GHActions-demo/.github/workflows/jobs.yml@main
    with:
       usernames: '["Again"]'
       hello_job: false
       goodbye_job: true
