name: Manual run
on:
  workflow_dispatch:
    inputs:
      names:
        description: 'Person to greet'
        type: string
        default: '["Manuel", "Roberto"]'
      hello:
        description: 'Hello'
        type: boolean
        default: false
      goodbye:
        description: 'Goodbye'
        type: boolean
        default: false
      sha:
        description: 'SHA'
        type: string
jobs:
  manual_test:
    name: manual test
    uses: gbetous-swir/GHActions-demo/.github/workflows/jobs.yml@main
    with:
       # As GitHub Interface returns a string even on boolean type, lcast it to real boolean
       usernames:  ${{ github.event.inputs.names }}
       hello_job:  ${{ github.event.inputs.hello == 'true' }}
       goodbye_job:  ${{ github.event.inputs.goodbye == 'true' }}
